### ISSUE TITLE
Possible value of the project

### ISSUE THREAD

**Issue by gevorgyana** [sourcegraph/scip-clang#11] opened 2022-12-23 14:50 UTC
Hi team.
this is open source and I plan to contribute. Although I don't know how much time I have for this project. Also I am pretty noob in this domain. But here is the potential value of shaping up a good and fast indexing system for querying ref/def relations & understanding the roadmap of codepath.

Please check this link. GitHub currently uses TreeSitter which is kind of slow so I guess that using Clang may be beneficial. I am no expert, this is jus a hypothesis. Feel free to comment. 

In the meantime, I will try to find time to contribute. Let's stay in touch and maybe coordinate our work here.

[1] https://github.com/orgs/community/discussions/8594#discussioncomment-4402160

**Comment by varungandhi-src** [comment] 2022-12-28 03:44
> Please check this link. GitHub currently uses TreeSitter which is kind of slow so I guess that using Clang may be beneficial. I am no expert, this is jus a hypothesis. Feel free to comment.

The problem is not that tree-sitter is slow; the problem is that it is not (and cannot be, by design) 100% accurate (= no false positives, no false negative). In C++, like with many other languages, name resolution and type-checking are intertwined, so you can't have a fully correct implementation of name resolution without having a type-checker. Implementing a C++ type-checker is very complicated, which is why we're building on top of Clang here.

You can have an approximate implementation of type-checking, sure, and depending on the language features being used, it may or may not work decently. But this project is not about working decently; it needs to be at least as good as navigation in an IDE. The VS Code extension clangd also builds on top of Clang for this same reason. Code navigation inside Xcode uses SourceKit (which builds on top of the Swift compiler for Swift and Apple Clang for C++). A tree-sitter based navigation solution cannot provide the same fidelity.

So while I think there is some high-level overlap between goals (code navigation), the details are quite different, which motivates the different design choices.

> In the meantime, I will try to find time to contribute.

To set expectations here; it's a bit too early right now, the project skeleton not even fully in place. It will probably be at least a month or two more before this project is able to take OSS contributions.

**Comment by varungandhi-src** [comment] 2022-12-28 03:49
I'm closing this issue because there's no specific resolution coming up right now. Feel free to "Watch" this repo (near the top right in the GitHub desktop UI) in case you'd like to be notified of new issues being filed.

If/when we have beginner-friendly issues that are not on the critical path, I can tag you if you're still interested.

**Closed by varungandhi-src** 2022-12-28 03:49 UTC

**Comment by gevorgyana** [comment] 2022-12-28 14:04
Yes, please leave a tag if possible
